name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REPO_NAME: ${{ vars.DOCKER_REPO_PREFIX}}/${{ github.event.repository.name }} # devops/hello-world
  FULL_IMAGE_NAME: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPO_PREFIX}}/${{ github.event.repository.name }} # 1234.eu-west-2.ecr.amazonaws.com/devops/hello-world
  TAG_NAME: ${{ github.ref_name }} # v1.2.34

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ vars.ECR_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure repo
        run: aws ecr describe-repositories --repository-names ${{ env.REPO_NAME }} || aws ecr create-repository --repository-name ${{ env.REPO_NAME }}

      - name: Build and push Docker image for Lambda
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.REPO_NAME }}
          IMAGE_TAG: ${{ env.TAG_NAME }}
        run: |
          docker buildx build --platform linux/amd64 \
            --provenance=false --progress=plain \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            -f Dockerfile \
            --push .